# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='button',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
